# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designerID', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=250)),
                ('firmname', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='designer',
            name='designerPro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designers.Designers'),
        ),
    ]
