# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers',
            name='design',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='designers',
            name='password',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='designers',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
