# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-24 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_auto_20161225_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designers',
            name='password',
        ),
    ]
