# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-25 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_remove_designers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
