# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0006_auto_20170114_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='designers',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
