# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0007_auto_20170114_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers',
            name='portfolio1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='designers',
            name='portfolio2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='designers',
            name='portfolio3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='designers',
            name='points',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
