# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0008_auto_20170118_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designers',
            old_name='portfolio1',
            new_name='design1',
        ),
        migrations.RenameField(
            model_name='designers',
            old_name='portfolio2',
            new_name='design2',
        ),
        migrations.RenameField(
            model_name='designers',
            old_name='portfolio3',
            new_name='design3',
        ),
        migrations.RenameField(
            model_name='designers',
            old_name='design',
            new_name='profilepic',
        ),
    ]
