# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0009_auto_20170119_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='designers',
            name='AboutMe',
            field=models.TextField(default='Please tell us about your personallity and why shoud customers be interested in you', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designers',
            name='AboutYourDesigns',
            field=models.TextField(default='Please tell us about your design styles', max_length=200, null=True),
        ),
    ]
